# /etc/sudoers.d/[USERNAME] must be set to NOPASSWD:ALL

- hosts: localhost
  become: true
  tasks:
    # - include: repos.yml sudoers.yml base.yml desktop.yml
    - name: "Enable i386 Packages"
      command: dpkg --add-architecture i386
      register: multiarch_status
    # - file:
    #     path: /home/weaverg/test.txt
    #     state: file
    - name: "Install apt-transport-https package(s) and dependencies for Apt"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    - name: "Install Core Packages"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - curl

    - name: "Google Chrome Apt Repository"
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
      tags:
        - apt-repository

    - name: "Jenkins Apt Repository"
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins
      tags:
        - apt-repository

    - name: "Debian Apt Repository - Contrib"
      apt_repository:
        repo: deb http://debian.osuosl.org/debian/ stretch contrib
        state: present
        filename: debian-contrib
      tags:
        - apt-repository

    - name: "Debian Apt Repository - Non-Free"
      apt_repository:
        repo: deb http://debian.osuosl.org/debian/ stretch non-free
        state: present
        filename: debian-non-free
      tags:
        - apt-repository

    - name: "Sublime Text Apt Repository"
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublime-text
      tags:
        - apt-repository

    - name: "Docker Apt Repository"
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present
        filename: docker
      tags:
        - apt-repository

    - name: "Docker Apt Repository Key"
      command: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -

    - name: "Update Apt cache"
      apt:
        update_cache: true

    - name: "Add weaverg sudoers.d/ file"
      template: 
        src: templates/sudoers.weaverg.j2
        dest: /etc/sudoers.d/weaverg

    - name: "Install Sublime Text"
      apt: 
        name: sublime-text
        state: latest

    - name: "Install Google Chrome"
      apt: 
        name: google-chrome-stable
        state: latest

    - name: "Install Docker"
      apt: 
        name: docker-ce
        state: latest

    - name: "Install Linux Headers - AMD64"
      apt: 
        name: linux-headers-amd64
        state: latest

    # - name: "Install NVIDIA Driver"
    #   apt: 
    #     name: nvidia-driver
    #     state: present

    # - name: "Install Steam"
    #   apt: 
    #     name: steam
    #     state: present

    - name: "Install OpenJDK 8"
      apt: 
        # name: openjdk-8-jre
        name: openjdk-8-jdk
        state: latest

# Ruby
# Python

# playbook-base
# playbook-base-jdk
# etc, etc.